### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by adriendelsalle** [ssg-aero/yams#1]
Description
---

Thanks for the project!

Is the license `GPL` or `LGPL`?
I noticed `LGPL` in the [conda recipe](https://github.com/ssg-aero/yams/blob/4762a16cdc1f4c324712748b1b23330a36e7e8ba/recipe/meta.yaml#L43) and `GPL` in the [license file](https://github.com/ssg-aero/yams/blob/master/LICENCE).

**Comment by ssg-aero** [comment]
LGPL, file will be updated in the next release.

Regards.
